# config/packages/doctrine.yaml
doctrine:
  dbal:
    # Configurez la connexion à PostgreSQL
    driver: 'pdo_pgsql'
    server_version: '12'
    charset: utf8
    default_table_options:
      charset: utf8
      collate: utf8_unicode_ci

    # Mettez à jour avec vos informations de connexion PostgreSQL
    url: '%env(resolve:DATABASE_URL)%'

  orm:
    auto_generate_proxy_classes: true
    naming_strategy: doctrine.orm.naming_strategy.underscore
    auto_mapping: true
